# AGP 9.x properties
# These are required to keep our explicit Kotlin plugin working (AGP 10 will change this)
android.builtInKotlin=false
android.newDsl=false

# Actual project settings
android.useAndroidX=true
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
# Ugg! JVM must eat and spit UTF-8 everywhere, else Ä Ö Ü turn to question rocks.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
